### ISSUE TITLE
Magento-Image-Color-Switcher-Module

### ISSUE THREAD

**Issue by navinmsoo7** [gayanhewa/Color-Swatch#2]
hey guys, i copied all the files in my magento, but this module not working can you tell me how to do this .......?

Thanks

**Comment by gayanhewa** [comment]
@navinmsoo7 please provide more information. ie. which version of Magento etc.

**Comment by navinmsoo7** [comment]
Magento ver. 1.9.2.1
http://www.ohmydiamonds.com/index.php/default/engagement-rings/classic-solitaire-engagement-rings/m1008-a1.html

plz check links

**Comment by navinmsoo7** [comment]
Magento ver. 1.9.2.1
http://www.ohmydiamonds.com/index.php/default/engagement-rings/classic-solitaire-engagement-rings/m1008-a1.htmlMagento
ver. 1.9.2.1
http://www.ohmydiamonds.com/index.php/default/engagement-rings/classic-solitaire-engagement-rings/m1008-a1.html

**Comment by gayanhewa** [comment]
hey @navinmsoo7 , the module is tested only on 1.7. There might be some issues which you would have to address. Feel free to send a pull request.
